workspace = { members = ["ghidra_sleigh"] }

[package]
name = "sleigh"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sleigh"
path = "src/main.rs"

[dependencies]
nom = "6.0"
bitvec = "1"
glob = "0.3.1"
elementtree = "1.2.3"
lazy_static = "1.4.0"
clap = { version = "4.5.26", features = ["derive"] }

[dev-dependencies]
ghidra_sleigh = { path = "ghidra_sleigh" }
