workspace = { members = [ "ghidra_sleigh"] }

[package]
name = "pcode"
version = "0.1.0"
edition = "2021"
description = "Pure Rust implementation of a p-code disassembler and lifter."
license = "MIT OR Apache-2.0"

[[bin]]
name = "pcode"
path = "src/main.rs"

[dependencies]
nom = "6.0"
bitvec = "1"
glob = "0.3.1"
elementtree = "1.2.3"
clap = { version = "4.5.26", features = ["derive"] }
flexstr = "0.9.2"
object = "0.35.0"

[dev-dependencies]
ghidra_sleigh = { path = "ghidra_sleigh" }
