use std::fmt;

#[repr(u32)]
#[derive(PartialEq, Eq, Hash, Copy, Clone)]
pub enum OpCode {
    Copy = 1,
    Load,
    Store,
    Branch,
    CBranch,
    BranchInd,
    Call,
    CallInd,
    CallOther,
    Return,
    IntEqual,
    IntNotEqual,
    IntSLess,
    IntSLessEqual,
    IntLess,
    IntLessEqual,
    IntZext,
    IntSext,
    IntAdd,
    IntSub,
    IntCarry,
    IntSCarry,
    IntSBorrow,
    Int2Comp,
    IntNegate,
    IntXor,
    IntAnd,
    IntOr,
    IntLeft,
    IntRight,
    IntSRight,
    IntMult,
    IntDiv,
    IntSDiv,
    IntRem,
    IntSRem,
    BoolNegate,
    BoolXor,
    BoolAnd,
    BoolOr,
    FloatEqual,
    FloatNotEqual,
    FloatLess,
    FloatLessEqual,
    FloatNan,
    FloatAdd,
    FloatDiv,
    FloatMult,
    FloatSub,
    FloatNeg,
    FloatAbs,
    FloatSqrt,
    FloatInt2Float,
    FloatFloat2Float,
    FloatTrunc,
    FloatCeil,
    FloatFloor,
    FloatRound,
    MultiEqual,
    Indidrect,
    Piece,
    SubPiece,
    Cast,
    PtrAdd,
    PtrSub,
    SegmentOp,
    CPoolRef,
    New,
    Insert,
    Extract,
    PopCount,
}

impl fmt::Display for OpCode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let opstr = match self {
            &OpCode::Copy => "Copy",
            &OpCode::Load => "Load",
            &OpCode::Store => "Store",
            &OpCode::Branch => "Branch",
            &OpCode::CBranch => "CBranch",
            &OpCode::BranchInd => "BranchInd",
            &OpCode::Call => "Call",
            &OpCode::CallInd => "CallInd",
            &OpCode::CallOther => "CallOther",
            &OpCode::Return => "Return",
            &OpCode::IntEqual => "IntEqual",
            &OpCode::IntNotEqual => "IntNotEqual",
            &OpCode::IntSLess => "IntSLess",
            &OpCode::IntSLessEqual => "IntSLessEqual",
            &OpCode::IntLess => "IntLess",
            &OpCode::IntLessEqual => "IntLessEqual",
            &OpCode::IntZext => "IntZext",
            &OpCode::IntSext => "IntSext",
            &OpCode::IntAdd => "IntAdd",
            &OpCode::IntSub => "IntSub",
            &OpCode::IntCarry => "IntCarry",
            &OpCode::IntSCarry => "IntSCarry",
            &OpCode::IntSBorrow => "IntSBorrow",
            &OpCode::Int2Comp => "Int2Comp",
            &OpCode::IntNegate => "IntNegate",
            &OpCode::IntXor => "IntXor",
            &OpCode::IntAnd => "IntAnd",
            &OpCode::IntOr => "IntOr",
            &OpCode::IntLeft => "IntLeft",
            &OpCode::IntRight => "IntRight",
            &OpCode::IntSRight => "IntSRight",
            &OpCode::IntMult => "IntMult",
            &OpCode::IntDiv => "IntDiv",
            &OpCode::IntSDiv => "IntSDiv",
            &OpCode::IntRem => "IntRem",
            &OpCode::IntSRem => "IntSRem",
            &OpCode::BoolNegate => "BoolNegate",
            &OpCode::BoolXor => "BoolXor",
            &OpCode::BoolAnd => "BoolAnd",
            &OpCode::BoolOr => "BoolOr",
            &OpCode::FloatEqual => "FloatEqual",
            &OpCode::FloatNotEqual => "FloatNotEqual",
            &OpCode::FloatLess => "FloatLess",
            &OpCode::FloatLessEqual => "FloatLessEqual",
            &OpCode::FloatNan => "FloatNan",
            &OpCode::FloatAdd => "FloatAdd",
            &OpCode::FloatDiv => "FloatDiv",
            &OpCode::FloatMult => "FloatMult",
            &OpCode::FloatSub => "FloatSub",
            &OpCode::FloatNeg => "FloatNeg",
            &OpCode::FloatAbs => "FloatAbs",
            &OpCode::FloatSqrt => "FloatSqrt",
            &OpCode::FloatInt2Float => "FloatInt2Float",
            &OpCode::FloatFloat2Float => "FloatFloat2Float",
            &OpCode::FloatTrunc => "FloatTrunc",
            &OpCode::FloatCeil => "FloatCeil",
            &OpCode::FloatFloor => "FloatFloor",
            &OpCode::FloatRound => "FloatRound",
            &OpCode::MultiEqual => "MultiEqual",
            &OpCode::Indidrect => "Indidrect",
            &OpCode::Piece => "Piece",
            &OpCode::SubPiece => "SubPiece",
            &OpCode::Cast => "Cast",
            &OpCode::PtrAdd => "PtrAdd",
            &OpCode::PtrSub => "PtrSub",
            &OpCode::SegmentOp => "SegmentOp",
            &OpCode::CPoolRef => "CPoolRef",
            &OpCode::New => "New",
            &OpCode::Insert => "Insert",
            &OpCode::Extract => "Extract",
            &OpCode::PopCount => "PopCount",
        };
        write!(f, "{}", opstr)
    }
}
