use std::fmt;

#[repr(u32)]
#[derive(PartialEq, Eq, Hash, Copy, Clone)]
pub enum OpCode {
    Copy = 1,
    Load,
    AddrOf,
    Store,
    Branch,
    CBranch,
    BranchInd,
    Call,
    CallInd,
    CallOther,
    Return,
    IntEqual,
    IntNotEqual,
    IntSLess,
    IntSLessEqual,
    IntLess,
    IntLessEqual,
    IntSGreater,
    IntSGreaterEqual,
    IntGreater,
    IntGreaterEqual,
    IntZext,
    IntSext,
    IntAdd,
    IntSub,
    IntCarry,
    IntSCarry,
    IntSBorrow,
    Int2Comp,
    IntNegate,
    IntXor,
    IntAnd,
    IntOr,
    IntLeft,
    IntRight,
    IntSRight,
    IntMult,
    IntDiv,
    IntSDiv,
    IntRem,
    IntSRem,
    BoolNegate,
    BoolXor,
    BoolAnd,
    BoolOr,
    FloatEqual,
    FloatNotEqual,
    FloatLess,
    FloatLessEqual,
    FloatNan,
    FloatAdd,
    FloatDiv,
    FloatMult,
    FloatSub,
    FloatNeg,
    FloatAbs,
    FloatSqrt,
    FloatInt2Float,
    FloatFloat2Float,
    FloatTrunc,
    FloatCeil,
    FloatFloor,
    FloatRound,
    MultiEqual,
    Indidrect,
    Piece,
    SubPiece,
    Cast,
    PtrAdd,
    PtrSub,
    SegmentOp,
    CPoolRef,
    New,
    Insert,
    Extract,
    PopCount,
    Label,
}

impl OpCode {
    pub fn is_conditional(&self) -> bool {
        use OpCode::*;
        matches!(self, 
            IntEqual |
            IntNotEqual |
            IntSLess |
            IntSLessEqual |
            IntLess |
            IntLessEqual |
            IntCarry |
            IntSCarry |
            IntSBorrow
        )
    }

    fn to_string(&self) -> String {
        match self {
            &OpCode::Copy => "Copy",
            &OpCode::Load => "Load",
            &OpCode::AddrOf => "AddrOf",
            &OpCode::Store => "Store",
            &OpCode::Branch => "Branch",
            &OpCode::CBranch => "CBranch",
            &OpCode::BranchInd => "BranchInd",
            &OpCode::Call => "Call",
            &OpCode::CallInd => "CallInd",
            &OpCode::CallOther => "CallOther",
            &OpCode::Return => "Return",
            &OpCode::IntEqual => "IntEqual",
            &OpCode::IntNotEqual => "IntNotEqual",
            &OpCode::IntSLess => "IntSLess",
            &OpCode::IntSLessEqual => "IntSLessEqual",
            &OpCode::IntLess => "IntLess",
            &OpCode::IntLessEqual => "IntLessEqual",
            &OpCode::IntSGreater => "IntSGreater",
            &OpCode::IntSGreaterEqual => "IntSGreaterEqual",
            &OpCode::IntGreater => "IntGreater",
            &OpCode::IntGreaterEqual => "IntGreaterEqual",
            &OpCode::IntZext => "IntZext",
            &OpCode::IntSext => "IntSext",
            &OpCode::IntAdd => "IntAdd",
            &OpCode::IntSub => "IntSub",
            &OpCode::IntCarry => "IntCarry",
            &OpCode::IntSCarry => "IntSCarry",
            &OpCode::IntSBorrow => "IntSBorrow",
            &OpCode::Int2Comp => "Int2Comp",
            &OpCode::IntNegate => "IntNegate",
            &OpCode::IntXor => "IntXor",
            &OpCode::IntAnd => "IntAnd",
            &OpCode::IntOr => "IntOr",
            &OpCode::IntLeft => "IntLeft",
            &OpCode::IntRight => "IntRight",
            &OpCode::IntSRight => "IntSRight",
            &OpCode::IntMult => "IntMult",
            &OpCode::IntDiv => "IntDiv",
            &OpCode::IntSDiv => "IntSDiv",
            &OpCode::IntRem => "IntRem",
            &OpCode::IntSRem => "IntSRem",
            &OpCode::BoolNegate => "BoolNegate",
            &OpCode::BoolXor => "BoolXor",
            &OpCode::BoolAnd => "BoolAnd",
            &OpCode::BoolOr => "BoolOr",
            &OpCode::FloatEqual => "FloatEqual",
            &OpCode::FloatNotEqual => "FloatNotEqual",
            &OpCode::FloatLess => "FloatLess",
            &OpCode::FloatLessEqual => "FloatLessEqual",
            &OpCode::FloatNan => "FloatNan",
            &OpCode::FloatAdd => "FloatAdd",
            &OpCode::FloatDiv => "FloatDiv",
            &OpCode::FloatMult => "FloatMult",
            &OpCode::FloatSub => "FloatSub",
            &OpCode::FloatNeg => "FloatNeg",
            &OpCode::FloatAbs => "FloatAbs",
            &OpCode::FloatSqrt => "FloatSqrt",
            &OpCode::FloatInt2Float => "FloatInt2Float",
            &OpCode::FloatFloat2Float => "FloatFloat2Float",
            &OpCode::FloatTrunc => "FloatTrunc",
            &OpCode::FloatCeil => "FloatCeil",
            &OpCode::FloatFloor => "FloatFloor",
            &OpCode::FloatRound => "FloatRound",
            &OpCode::MultiEqual => "MultiEqual",
            &OpCode::Indidrect => "Indidrect",
            &OpCode::Piece => "Piece",
            &OpCode::SubPiece => "SubPiece",
            &OpCode::Cast => "Cast",
            &OpCode::PtrAdd => "PtrAdd",
            &OpCode::PtrSub => "PtrSub",
            &OpCode::SegmentOp => "SegmentOp",
            &OpCode::CPoolRef => "CPoolRef",
            &OpCode::New => "New",
            &OpCode::Insert => "Insert",
            &OpCode::Extract => "Extract",
            &OpCode::PopCount => "PopCount",
            &OpCode::Label => "Label",
        }.to_string()
    }
}

impl fmt::Debug for OpCode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.to_string())
    }
}

impl fmt::Display for OpCode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.to_string())
    }
}

impl OpCode {
    pub fn from_str(s: &str) -> Self {
        match s {
            "COPY" => OpCode::Copy,
            "LOAD" => OpCode::Load,
            "STORE" => OpCode::Store,
            "BRANCH" => OpCode::Branch,
            "CBRANCH" => OpCode::CBranch,
            "BRANCHIND" => OpCode::BranchInd,
            "CALL" => OpCode::Call,
            "CALLIND" => OpCode::CallInd,
            "CALLOTHER" => OpCode::CallOther,
            "RETURN" => OpCode::Return,
            "INT_EQUAL" => OpCode::IntEqual,
            "INT_NOTEQUAL" => OpCode::IntNotEqual,
            "INT_SLESS" => OpCode::IntSLess,
            "INT_SLESSEQUAL" => OpCode::IntSLessEqual,
            "INT_LESS" => OpCode::IntLess,
            "INT_LESSEQUAL" => OpCode::IntLessEqual,
            "INT_ZEXT" => OpCode::IntZext,
            "INT_SEXT" => OpCode::IntSext,
            "INT_ADD" => OpCode::IntAdd,
            "INT_SUB" => OpCode::IntSub,
            "INT_CARRY" => OpCode::IntCarry,
            "INT_SCARRY" => OpCode::IntSCarry,
            "INT_SBORROW" => OpCode::IntSBorrow,
            "INT_2COMP" => OpCode::Int2Comp,
            "INT_NEGATE" => OpCode::IntNegate,
            "INT_XOR" => OpCode::IntXor,
            "INT_AND" => OpCode::IntAnd,
            "INT_OR" => OpCode::IntOr,
            "INT_LEFT" => OpCode::IntLeft,
            "INT_RIGHT" => OpCode::IntRight,
            "INT_SRIGHT" => OpCode::IntSRight,
            "INT_MULT" => OpCode::IntMult,
            "INT_DIV" => OpCode::IntDiv,
            "INT_SDIV" => OpCode::IntSDiv,
            "INT_REM" => OpCode::IntRem,
            "INT_SREM" => OpCode::IntSRem,
            "BOOL_NEGATE" => OpCode::BoolNegate,
            "BOOL_XOR" => OpCode::BoolXor,
            "BOOL_AND" => OpCode::BoolAnd,
            "BOOL_OR" => OpCode::BoolOr,
            "FLOAT_EQUAL" => OpCode::FloatEqual,
            "FLOAT_NOTEQUAL" => OpCode::FloatNotEqual,
            "FLOAT_LESS" => OpCode::FloatLess,
            "FLOAT_LESSEQUAL" => OpCode::FloatLessEqual,
            "FLOAT_NAN" => OpCode::FloatNan,
            "FLOAT_ADD" => OpCode::FloatAdd,
            "FLOAT_DIV" => OpCode::FloatDiv,
            "FLOAT_MULT" => OpCode::FloatMult,
            "FLOAT_SUB" => OpCode::FloatSub,
            "FLOAT_NEG" => OpCode::FloatNeg,
            "FLOAT_ABS" => OpCode::FloatAbs,
            "FLOAT_SQRT" => OpCode::FloatSqrt,
            "INT2FLOAT" => OpCode::FloatInt2Float,
            "FLOAT2FLOAT" => OpCode::FloatFloat2Float,
            "TRUNC" => OpCode::FloatTrunc,
            "CEIL" => OpCode::FloatCeil,
            "FLOOR" => OpCode::FloatFloor,
            "ROUND" => OpCode::FloatRound,
            "MULTIEQUAL" => OpCode::MultiEqual,
            "INDIRECT" => OpCode::Indidrect,
            "PIECE" => OpCode::Piece,
            "SUBPIECE" => OpCode::SubPiece,
            "CAST" => OpCode::Cast,
            "PTRADD" => OpCode::PtrAdd,
            "PTRSUB" => OpCode::PtrSub,
            "SEGMENTOP" => OpCode::SegmentOp,
            "CPOOLREF" => OpCode::CPoolRef,
            "NEW" => OpCode::New,
            "INSERT" => OpCode::Insert,
            "EXTRACT" => OpCode::Extract,
            "POPCOUNT" => OpCode::PopCount,
            "LABEL" => OpCode::Label,
            _ => panic!("{}", s)
        }
    }
}
